version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: KATERYNKA
      POSTGRES_PASSWORD: ps
      POSTGRES_DB: msdb
    ports:
      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data  # Persist data outside container

volumes:
  postgres-data: